### ISSUE TITLE
cursor gets caught on mid-air robots

### ISSUE THREAD

**Issue by LevFendi** [Factorio-Access/FactorioAccess#139]
This issue makes cursor skipping difficult to use. Therefore construction robots and logistic robots can be excluded from cursor skipping checks.

**Comment by ahicks92** [comment]
They're still ignored when skipping.  This should probably be closed unless we're also including the stationary/not skipping parts.  I only had to revert the latter.

**Comment by LevFendi** [comment]
I am glad that cursor skipping ignores them, but another aspect of this issue was to make regular tile reading select entities other than the robots (and remnants) if these other entities exist.

As for how to achieve the selection of a specific ent on a tile with many overlapping ents, we can use the `player.selected`, `selection_priority`, and related API features mentioned yesterday on Discord by @EphDoering.

**Comment by ahicks92** [comment]
I know we're doing both, they're both because of me.  But I couldn't find a second issue so wasn't clear if we were tracking it here.

We can use the APIs from Discord eventually but for a first pass I want to avoid them.  That's a much larger problem.  They are very possibly a great choice--I haven't looked yet--but the worst world isn't one or the other, it's confusing everything by trying to move over incrementally.  The first step of doing so has to be centralizing the idea of what a selection is, so that code making those decisions is calling into something unified.  This puts us in a place where we can change the interpretation without being split-brain.  I genuinely have no idea how hard that is, not even to the order of magnitude; it may even be (mostly) done.

Otherwise probably the class of bugs becomes "selecting two things at once" where half the mod code is working on a and the other half on b simultaneously.

I'd suggest that you move that to another issue and maybe put some notes in it wrt what the mod does now vs what you want it to do with the api.
