### ISSUE TITLE
Speed up building blueprints towards the north and west

### ISSUE THREAD

**Issue by LevFendi** [Factorio-Access/FactorioAccess#151]
## **1. Describe the existing behavior and what problems it does or might create**
When you place down a blueprint and head east or south, you can quickly cursor skip over the ghosts and place down another copy. The same is not true for heading north and west, because you need to count out the length or height of the blueprint with respect to the last placed ghosts.

## **2. Describe the change you'd like**
If a type of cursor skipping allows you to skip by the height or length of the blueprint respectively, it would be much easier to tile a blueprint in any direction.

## **3. Describe alternatives you've considered, if any, perhaps including previous discussions**
A proposed alternative is t allow setting a rectangular cursor size that equals the blueprint dimensions so that moving the enlarged cursor would move it by the same dimensions as the blueprint.

**Comment by ahicks92** [comment]
To go ahead and repost what I put on discord, two problems.

First if you're holding something small (e.g. small electric pole) you're now locked into cursor skips too small to be useful.  I find that having it on the standard keys now means managing the hand contents just to look for ends of belts or such.  Also no more skipping a long row of buildings if holding something etc.  Even with blueprints it's useful for normal skipping to work to find the place to be.

Second there's, call it an off by 1.  Skip a row of buildings while holding a blueprint. You'll end up either early because there was some ground before the corner you want to get to, or late because the first skip gets to the end, the second skip gets to one ground tile off, and the third skip skips the blueprint.  Fixing such things is a nightmare at least ATM, I believe even in Vanilla: rebuilding is fine, rebuilding to fix a one-tile mistake though...

This will also probably completely throw new users as it is because afaik people already have trouble with the hand, and now it being empty means something else, and also if it's not on your quickbar to put back, just...no.  I'm experienced and I still "just god no" it.

My suggestion: commandeer alt+i, call it the mode key, stick skip by preview in it.  We can make a third mode for "smart" skipping later and put it in the same place.  I'm open to more convenient ideas, though, but we're stuck between the key budget wall and the confusing/inconvenient hard place, as it were.

**Comment by ahicks92** [comment]
Well, if we have modes maybe not even skip by preview, just a mode where you press keys and move by preview all the time. That'd be damn useful, assembly machine lines would just be right, click, right, click, right... click...

**Comment by LevFendi** [comment]
Closed alongside #163
