### ISSUE TITLE
Allow setting 50% zoom by pressing a button

### ISSUE THREAD

**Issue by LevFendi** [Factorio-Access/FactorioAccess#210]
The dev stream has emphasized that blind players who want to screen share will not know the current zoom level, and how visible it is for a sighted audience. I propose to fix this by allowing users to press a button, such as middle clicking the mouse, and thus resetting the zoom to a fixed medium value like 50%. 

The 50% value would be a sweet spot between covering a wide area on screen and having the individual buildings large enough to differentiate with ease.

The fixed zoom value would also mean standardization for the blind player about how much of the area around them is on screen. While the "distant" tile reporting feature gives this info on the spot, it is easier to just memorize the fixed zoom ranges.

**Comment by EphDoering** [comment]
I think there's currently a different event for that.

**Comment by ahicks92** [comment]
What is this even about?

**Comment by LevFendi** [comment]
I will rename this and explain it to better represent my intention.

**Comment by ahicks92** [comment]
O cool, still debating if I want to do more streams or not but probably I will after rulers are knocked into shape because just imagine how less explanatory my other stream would have been.

I would consider maybe binding this to the keyboard because now that KK is working I don't think having a mouse plugged in or anywhere near you is required anymore.  Someone sighted should really test that to be honest and see what falls down where.

**Comment by LevFendi** [comment]
Added to main in abff70ca1abac61433c7b28ccbc3b1a016db45df
Controls:
- Set standard zoom: ALT + Z
- Set closest zoom: SHIFT + ALT + Z
- Set furthest zoom: CONTROL + ALT + Z
