### ISSUE TITLE
handle rename of surface on LuaPlayer to physical_surface

### ISSUE THREAD

**Issue by ahicks92** [Factorio-Access/FactorioAccess#283]
Exactly what it says.  This is an interim thing.  Eventually we need to be getting surfaces through the cursor module or whatever but as long as it's just 2.0 then we're fine to just rename the field globally.  Finding these is going to be a pain however, probably wait for a crash and hit it.

**Comment by EphDoering** [comment]
I'm not sure we want to change this? I think LuaPlayer still inherits surface from LuaControl. So I'm pretty sure this ties in strongly with remote view where the player is viewing/changing things on a different surface from their character. But I'd imagine that we want to use the surface that the player is actively viewing which I think will still be just surface rather than physical_surface.

**Comment by ahicks92** [comment]
I didn't notice that it's not a rename. Will look at some point.  My guess is that we want physical_surface because that's what the mod "understands" right now, but if it's not a rename then maybe we can wait on it.

**Comment by ahicks92** [comment]
This whole thing is, well, a thing.  As regards this ticket, though, closing because there's no real relation to reality.  In reality surface, physical_surface, and the character's surface are all related in various ways and whenever we get as far as space age we're going to have to figure that out.  It does however turn out that using .surface works for 2.0 base.
