### ISSUE TITLE
Walking in cursor mode (character nudging)

### ISSUE THREAD

**Issue by LevFendi** [Factorio-Access/FactorioAccess#80]
Help wanted about how to map controls.

First consider the inputs we need in cursor mode:
1) move cursor
2) move character
3) move enlarged cursor by step size
4) cursor skip
5) nudge buildings

Next consider that we have the following input schemes:
1) W A S D
2) SHIFT + W A S D
3) arrow keys
4) SHIFT + arrow keys
5) numpad keys
6) CONTROL + SHIFT + WASD

Ideally we want the bracket keys on the right hand and the WASD on the left hand, when building is involved.

**Comment by LevFendi** [comment]
I am thinking of having these in cursor mode:
1. move cursor with WASD (because bracket keys should be accessible)
2. skip cursor with SHIFT + WASD (because it should be similar to move-cursor)
3. move character with arrow keys 
4. move enlarged cursor with shift + arrow keys OR numpad keys

Also Note:
5. nudge buildings: CONTROL + SHIFT + WASD (as before)
6. CONTROL + WASD are reserved for various other things
7. ALT + WASD are reserved for various other things
8. ALT + arrow keys are reserved as alternate scanner menu or train menu controls

**Comment by LevFendi** [comment]
For the vice versa part, in "normal" mode:
1. walk with WASD
2. Nothing special with SHIFT + WASD
3. move cursor with arrow keys
4. move enlarged cursor with shift + arrow keys OR numpad keys
5. When the character moves, the cursor snaps back to them.

**Comment by alex19EP** [comment]
> move cursor with WASD (because bracket keys should be accessible)

what about wasd in remote vew?

I understand that the brackets on the right hand are important, but the fact that in remote mode we should not use wasd suggests that it is still better to completely switch to cursor control with arrows. or with numpad.

and also if you consider that when controlling transport it is also not possible to use wasd for the cursor.

**Comment by LevFendi** [comment]
Ah yes, remote view has the extra issue of WASD not being usable because it pans the camera and we cannot unbind that. I should put in an official forum request for API access to that. I think the issue here is that remote view switches to an invisible controller entity who technically does indeed move with WASD.

**Comment by ahicks92** [comment]
Honestly still unclear why we want this.  Just have the char walk to the cursor.  Is the reasoning that this is easier to make happen or that we need it for something?

**Comment by LevFendi** [comment]
The scenario is that you are building in cursor mode and the cursor gets out of reach. You can TP to the cursor, move out of the way or something, and then keep building, all without letting go of the preview in hand. The flip side is that you are running somewhere or driving a vehicle and you want to look around without getting into cursor mode.

Given the key budget, other controls deserve higher priority but maybe the less popular keys such as the numpad keys can be used for this feature.

**Comment by ahicks92** [comment]
Right, but like just have the char walk away from the cursor?  That's why I'm not getting it.  We should be able to just handle walking for the user.  It's not particularly difficult to move away because it doesn't matter what away is, you just do a floodfill around the border of the building and go whichever way seems to have the most space.

I don't exactly object, it just seems like this would be a really bad ux for the problem it solves.  Driving the cursor and walking both fills me with dread and I know how to use it.  One question I always ask myself with this is how to teach it.  And if I think "o you kinda don't" then I don't want to do it.  I am reasonably certain that new users who come to the mod will hate it.

I want numpad keys for diagonal movement and skipping.  Please don't take those, or otherwise help me come up with a better control scheme.  This is basically 100% required for rails and I should open an issue I guess.  Ultimately it's diagonal cursor skipping or pressing something like 4 keys per segment (maybe 2, I'm not actually sure where the segment ends in that case) on a diagonal that's hundreds of segments long.  And that', that is why I avoid diagonals like the plague.

I suppose maybe alt+numpad for walking?  That's workable I guess.  Or, save me, more modes.  Guess if you've got a numpad there's also the 3 at the top etc (note however: you can't use insert because it conflicts with every screen reader except Voiceover).

**Comment by alex19EP** [comment]
> Right, but like just have the char walk away from the cursor?

for me it will be comparable to teleportation which I do not use.

It seems to me that when we make games accessible to blind people, it is very important to strike a balance where you don’t feel like the game is doing some things for you or making it too easy.

It’s one thing when you use cruise control or not, and another when the mod teleports you during construction or controls the character itself simply when you move the cursor.

**Comment by ahicks92** [comment]
Yeah so.  I mean firstly having this doesn't hurt me so do it if you guys want. But:

In sighted land they hold the run key and use the mouse to just go right where they want for the building part.  This is fast.

In FA land, if you really want this, you've got to move the cursor around one by one.  That's how it is today, but there's really no way to change that.  Assuming we can have continuous walking  controls (which we probably can via alt inputs), you'll have to repeatedly lose your place to find out what the character is running into,, and use the cursor to plan a path unless you literally arrange your factory layout to avoid that problem.  This means losing your cursor location on a regular basis and having to go back, or constraining your layouts.  Even if the mod handled walking automatically, we are still significantly slower by orders of magnitude than a sighted player.  Why do we want to make this worse in the name of equality or something?  What's it actually get us?  It really seems like handling it automatically is a much bigger step toward equality.

I'll also throw out that there are tons and tons of mods by and for the sighted that offer infinite building reach.  I mean fine okay it's not part of the default game and there are enough sighted players that it's not the majority but QOL Research has over 100k downloads and if you don't want to play it by actually doing the research you can just set it in the options.  And, there's a ton more like it, either doing just infinite reach or doing it as part of something else.  I don't think we should do infinite reach, I'm just saying that it's not like handling walking is something the sighted want to do either, and they don't just have it handled for them, they just go meh let's literally never have to take a step at all.

I think it's important to remember what the game is about.  This isn't an exploring game or a platformer.  The only real thing teleporting versus automatic walking changes is that automatic walking forces us to spend the time the sighted would on walking from A to B.  That's faster for them than what we could do manually even in some hypothetical perfect world just because you do regularly have to stop and check if you went too far or whatever as a blind player.  Admittedly going too far is why I opened #161, but that's quite some work and we're not in a place to do it yet.

Like...to finish this off.  It's great that we have a couple users who want the feature.  But planning isn't about the couple users, this takes key budget, we have to maintain it forever even if very very few people use it, I have yet to see a reason other than "this is something I want" for what makes it useful, it's "equality" but in a horribly complicated clunky way when we already have 90% or so if not more, and it's significantly more complicated than the sighted experience it's supposedly equal with.  @LevFendi can do it if he wants but if you want my support on this I'd like to see objective reasons for a terrible UX.  What does this let you do?  For that matter, other than not hitting teleport, what would this let you do that you can't do today?  "I'm not equal" feelings and philosophy isn't the problem here: the problem here is that games are supposed to be fun.

**Comment by LevFendi** [comment]
The feature serves a purpose akin to nudging buildings. You nudge the player when they are standing in the way of building something. It is good UX in that sense. It is preferable over automatically teleporting the player out of the way and it lets you keep the cursor in place. 

As for the key assignment, we can use the numpad keys or the shifted numpad keys for this. Which should be prioritized for which is debatable but you can always change your own keybinds.

**Comment by ahicks92** [comment]
Feel I should briefly acknowledge that I and Sir Fendi went over this on Discord.  My conclusion was that this is worth it for reasons I still don't entirely get and am unlikely to get fully, but at least good non-silly ones.  QED I withdraw my objection WRT only a couple users.

**Comment by LevFendi** [comment]
Here is the latest proposed list of controls for WASD and arrow keys and numpad keys:

## Summary
- WASD in cursor mode will be used for a few kinds of cursor shifting. 
- The arrow keys will be used for moving something by 1 tile, with that something being the cursor or building or character. They work the same inside and outside of cursor mode.
- The ALT versions of WASD and arrow keys will have special controls. They work the same inside and outside of cursor mode.
- Numpad keys will be used for duplicates of other things, but with the option to include diagonal directions.

## WASD

- NOTE: All forms of cursor skipping require using cursor mode.
  
- `WASD`: skip the cursor by its current size. Size 1 is normal cursor moving.
  
- `SHIFT + WASD`: skip the cursor to the next tile change.
  
- `CONTROL + WASD`: skip the cursor by the hand preview size.
  
- `CONTROL + SHIFT + WASD`: empty, but maybe a new cursor skip type.
  
- `ALT + WASD`: keyboard shortcuts:
  
  - `ALT + A`: run an area scan at the cursor. It is no longer automatic.
  - `ALT + W`: toggle walking mode.
  - `ALT + S`: toggle the cursor skipping mode.
  - `ALT + D`: grab a deconstruction planner.
- `ALT + SHIFT + WASD`: empty.
  
- `ALT + CONTROL + WASD`: empty.
  
- `ALT + CONTROL SHIFT + WASD`: keyboard shortcuts:
  
  - S to enable structure travel mode.
    
  - Others empty.
    

## Arrow Keys

- NOTE: These work both inside and outside of cursor mode but not inside menus.
  
- `ARROW KEYS`: move the cursor by 1.
  
- `SHIFT + ARROW KEYS`: nudge the selected building by 1.
  
- `CONTROL + ARROW KEYS`: nudge the character by 1.
  
- `CONTROL + SHIFT + ARROW KEYS`: empty.
  
- `ALT + ARROW KEYS`: Alternate scanner/rail builder controls:
  
  - `ALT + UP`: Scan list up.
    
  - `ALT + DOWN`: Scan list down.
    
  - `ALT + LEFT`: Quick build rail turn left.
    
  - `ALT + RIGHT`: Quick build rail turn right.
    
- `ALT + SHIFT + ARROW KEYS`: Alternate scanner/splitter controls:
  
  - `ALT + SHIFT + UP`: Scan selection up.
    
  - `ALT + SHIFT + DOWN`: Scan selection down.
    
  - `ALT + SHIFT + LEFT`: Splitter input left.
    
  - `ALT + SHIFT + RIGHT`: Splitter input right.
    
- `ALT + CONTROL + ARROW KEYS`: Alternate scanner/splitter controls:
  
  - `ALT + CONTROL + UP`: Scan category up.
    
  - `ALT + CONTROL + DOWN`: Scan category down.
    
  - `ALT + CONTROL + LEFT`: Splitter output left.
    
  - `ALT + CONTROL + RIGHT`: Splitter output right.
    
- `ALT + CONTROL + SHIFT + ARROW KEYS`: empty.
  

## Numpad Keys

- NOTE: These work both inside and outside of cursor mode.
  

- `NUMPAD KEYS`: move the cursor by 1, including diagonals.
  
- `SHIFT + NUMPAD KEYS`: skip the cursor to the next tile change, including diagonals.
  
- `CONTROL + NUMPAD KEYS`: empty.
  
- `CONTROL + SHIFT + NUMPAD KEYS`: empty.
  
- `ALT + NUMPAD KEYS`: empty.
  
- `ALT + SHIFT + NUMPAD KEYS`: empty.
  
- `ALT + CONTROL + NUMPAD KEYS`: empty.
  
- `ALT + CONTROL + SHIFT + NUMPAD KEYS`: empty.

**Comment by ahicks92** [comment]
Would the page up etc scanner controls be going away?
The rail builder and scanner controls being "close" seems a bit odd but it's at least efficient and I can't think of better.

Why are we changing skipping modes with alt+s or is that just for future ideas like my proposed smart cursor?

**Comment by LevFendi** [comment]
The alternate scanner controls are there for the people who do not have page up and page down keys. 

ALT + S is in preparation for the future, yes.

**Comment by ahicks92** [comment]
Yeah I know but the list above didn't seem to say alternate.  It's not a huge deal to change that--I'd get used to it, I assume everyone else could, and new players wouldn't know.

Similar problem with numpad but at some point we have to say too bad for practical reasons.

**Comment by LevFendi** [comment]
Character nudging has been added and the new control scheme has been applied. However, not all associated new features such as diagonal cursor skipping have been added. Those other topics can have new issues opened later on.
